concordion/concordion

src/main/java/org/concordion/internal/runner/DefaultConcordionRunner.java
src/test-dummies/java/spec/concordion/results/runTotals/Annotations.java
src/test-dummies/java/spec/concordion/results/runTotals/CompoundStatement.java
src/test-dummies/java/spec/concordion/results/runTotals/RuleWithCallback.java
src/test-dummies/resources/spec/concordion/results/runTotals/Annotations.html
src/test/java/spec/concordion/integration/junit4/CompoundStatement.java
src/test/java/spec/concordion/integration/junit4/Junit4Test.java
src/test/java/spec/concordion/integration/junit4/RuleWithCallback.java
src/test/java/spec/concordion/integration/junit4/RulesSupportedByJunit.java
src/test/resources/spec/concordion/command/run/Run.html
src/test/resources/spec/concordion/integration/junit4/Junit4.html
src/test/resources/spec/concordion/results/runTotals/RunTotals.html

On fields and methods when using the concordion:run command. It already worked in concordion tests when run "normally" by junit. I've got it working for the TestRule class but not the depreciated MethodRule class.

Added support for the JUnit Rule annotation

---

src/main/java/org/concordion/internal/FileTarget.java

With the new example command in Concordion 2.0, the specification name in the output contains a link to the specific example, for example: 
`/path/to/my/specification.html#Example1`
When pasted into a browser URL bar, the `#` is turned into a `%23` and the page is not found (tested with Firefox and Chrome).
By prefixing `file://` to the link, the link can be pasted into the browser URL bar and the page is found, for example:
`file:///path/to/my/specification.html#Example1`
/cc @drtimwright

Add file:/// to path of specification in output

---

src/main/java/org/concordion/internal/MultiPattern.java
src/main/java/org/concordion/internal/SimpleEvaluator.java
src/test/java/org/concordion/internal/MultiPatternTest.java

Hello team,
Simple expression validation logic has been refactored.
Previously it was creating list of regular expressions (as strings) each time validateEvaluationExpression() or validateSetVariableExpression() method called. This makes time consuming call Pattern#compile executed each time.
I have refactored this class to use new MultiPattern class that holds list of Patterns.
This compiles reqular expression just once during Pattern#matcher call and then reuse it. This operation is thread safe.
public API remains same, so no impact on other components. 
Please review jmh benchmark of String#matches() vs Pattern#matcher(String)#matches()
[jmh benchmark](https://www.dropbox.com/s/cxkvz8koktfihb4/Precompile_Recompile.zip?dl=0)
[jmh benchmark result on my …

Reuse Patterns in SimpleEvaluator

---

src/main/java/org/concordion/Concordion.java
src/main/java/org/concordion/api/AbstractCommand.java
src/main/java/org/concordion/api/AbstractCommandDecorator.java
src/main/java/org/concordion/api/Command.java
src/main/java/org/concordion/api/listener/ExampleEvent.java
src/main/java/org/concordion/internal/XMLSpecification.java
src/main/java/org/concordion/internal/command/ExampleCommand.java
src/main/java/org/concordion/internal/command/SpecificationCommand.java
src/test/java/spec/concordion/extension/AbstractExtensionTestCase.java
src/test/java/spec/concordion/extension/listener/ListenerTest.java
src/test/java/test/concordion/TestRig.java
src/test/java/test/concordion/extension/ConcordionBuildLogger.java
src/test/java/test/concordion/extension/DocumentParsingLogger.java
src/test/java/test/concordion/extension/ExampleLogger.java
src/test/java/test/concordion/extension/ExampleProcessingExtension.java
src/test/java/test/concordion/extension/ProcessingExtension.java
src/test/java/test/concordion/extension/SpecificationProcessingLogger.java
src/test/resources/spec/concordion/extension/listener/Listener.html

@drtimwright would you review please?
Two things to look at in particular:
1. In XMLSpecification.java, the typecasting of the root command to `SpecificationCommand` so that we can remove `finish()` method from `Command` interface (and add a `start()` method to `SpecificationCommand` without bloating `Command` interface further).
2. In the Listener.html spec, that the `before` example is run 3 times; before each of the 2 examples and then after them. I assume the last one is for any commands outside of the examples. Do you think we should special case this and only run the `before` example if the main spec has other commands?
cheers
/cc @andrew-sumner

Fix listener execution order

---

.travis.yml

See https://github.com/travis-ci/travis-ci/issues/5227 for further details.

Workaround for buffer overflow issue with OpenJDK 6 compile on Travis.

---

src/main/java/org/concordion/api/SpecificationConverter.java
src/main/java/org/concordion/internal/XMLSpecificationReader.java
src/main/java/org/concordion/internal/listener/BreadcrumbRenderer.java
src/main/java/org/concordion/internal/parser/markdown/MarkdownConverter.java

The ExcelExtension uses the specification name for an HTML header.
See concordion/concordion-excel-extension#5

Added specification name to SpecificaionConverter.

---

src/main/java/org/concordion/internal/SummarizingResultRecorder.java

Added some basic synchronisation to the summarising results recorder class to avoid concurrency problems in the parallel runner.

Add synchronisation to the results recorder class.

---

src/main/java/org/concordion/internal/FixtureInstance.java
src/main/java/org/concordion/internal/XMLSpecificationReader.java
src/main/java/org/concordion/internal/listener/BreadcrumbRenderer.java
src/main/java/org/concordion/internal/listener/SpecificationExporter.java
src/main/java/org/concordion/internal/util/SimpleFormatter.java
src/test/java/test/org/concordion/internal/util/SimpleFormatterTest.java

String.format() and String.toUpperCase() load the entire internationalization engine. Therefore, they consume much time on the .NET platform.
SimpleFormatter just uses string concatenation.
As only the first letter needs to be converted to upper case, this can be done with Character.toUpperCase(), which does not depend on internationalization.

performance: replace String.format with SimpleFormatter & toUpperCase on Character

---

src/main/java/org/concordion/Concordion.java
src/main/java/org/concordion/api/SpecificationLocator.java
src/main/java/org/concordion/internal/ClassNameAndTypeBasedSpecificationLocator.java
src/main/java/org/concordion/internal/ClassNameBasedSpecificationLocator.java
src/main/java/org/concordion/internal/ConcordionBuilder.java
src/main/java/org/concordion/internal/DocumentParser.java
src/main/java/org/concordion/internal/command/AssertEqualsCommand.java
src/main/java/org/concordion/internal/command/BooleanCommand.java
src/main/java/org/concordion/internal/command/ExampleCommand.java
src/main/java/org/concordion/internal/command/ExecuteCommand.java
src/main/java/org/concordion/internal/command/RunCommand.java
src/main/java/org/concordion/internal/command/SetCommand.java
src/main/java/org/concordion/internal/command/SpecificationCommand.java
src/main/java/org/concordion/internal/command/ThrowableCatchingDecorator.java
src/main/java/org/concordion/internal/command/ThrowableCaughtPublisher.java
src/main/java/org/concordion/internal/command/VerifyRowsCommand.java
src/main/java/org/concordion/internal/extension/ExtensionChecker.java
src/main/java/org/concordion/internal/listener/PageFooterRenderer.java
src/main/java/org/concordion/internal/runner/DefaultConcordionRunner.java
src/test/java/test/concordion/internal/ClassNameBasedSpecificationLocatorTest.java

Previous 2.0 changes ensured the SpecificationLocator interface didn't change, so that we didn't break the ExcelExtension, by introducing a new SpecificationLocatorWithType interface.
However, we now have a breaking change to the Source interface, and the ExcelExtension is being updated for Concordion 2.0.
This change moves the new method from SpecificationLocatorWithType to SpecificationLocator and deprecates the existing method in SpecificationLocator. It removes the SpecificationLocatorWithType interface.
While it is a breaking change, it's much cleaner than the previous solution and more workable moving forward.

Tidy up SpecificationLocator

---

src/test/java/spec/concordion/command/example/SpecCallingFailFastExamplesFixture.java
src/test/resources/spec/concordion/command/example/SpecCallingFailFastExamples.md
src/test/resources/spec/concordion/command/execute/FailFastPassthrough.html

Issue #144 is already fixed, this bakes in the functionality.
Also fixed typo in FailFastPassthrough spec.

Added spec for fail-fast on expected-to-fail example.

---

src/main/java/org/concordion/Concordion.java
src/main/java/org/concordion/api/SpecificationByExample.java
src/main/java/org/concordion/integration/junit4/ConcordionRunner.java
src/main/java/org/concordion/internal/SpecificationToSpecificationByExampleAdaptor.java
src/main/java/org/concordion/internal/XMLSpecification.java
src/main/java/org/concordion/internal/cache/RunResultsCache.java
src/main/java/org/concordion/internal/command/RunCommand.java
src/test-dummies/java/spec/concordion/command/example/ExamplesMarkedExpectedToFailFixture.java
src/test-dummies/java/spec/concordion/command/example/ExamplesMarkedUnimplementedFixture.java
src/test-dummies/java/spec/concordion/results/runTotals/ExpectedToFailWithExampleFixture.java
src/test-dummies/resources/spec/concordion/command/example/ExamplesMarkedExpectedToFail.html
src/test-dummies/resources/spec/concordion/command/example/ExamplesMarkedUnimplemented.html
src/test-dummies/resources/spec/concordion/results/runTotals/ExpectedToFailWithExample.md
src/test/java/spec/concordion/command/example/FixtureWithExampleHookMethodsFixture.java
src/test/java/spec/concordion/command/example/FixtureWithExampleInitialisationFixture.java
src/test/java/spec/concordion/command/example/FixtureWithExampleWithoutOuterExampleHookMethodsFixture.java
src/test/java/spec/concordion/command/example/FixtureWithExampleWithoutOuterExampleInitialisationFixture.java
src/test/java/spec/concordion/command/example/FixtureWithoutExampleHookMethodsFixture.java
src/test/resources/spec/concordion/annotation/ImplementationStatus.html
src/test/resources/spec/concordion/command/example/Example.html
src/test/resources/spec/concordion/command/example/FixtureWithExampleHookMethods.html
src/test/resources/spec/concordion/command/example/FixtureWithExampleInitialisation.html
src/test/resources/spec/concordion/command/example/FixtureWithExampleWithoutOuterExampleHookMethods.html
src/test/resources/spec/concordion/command/example/FixtureWithExampleWithoutOuterExampleInitialisation.html
src/test/resources/spec/concordion/command/example/FixtureWithoutExampleHookMethods.html
src/test/resources/spec/concordion/command/example/FixtureWithoutExampleInitialisation.html
src/test/resources/spec/concordion/results/runTotals/RunTotals.html

* Don't run a separate "outer" example if there are no Concordion commands outside of named examples (#187)
* Don't allow ExpectedToFail or Unimplemented annotations on fixtures where the specification has named examples (#189)
* Fix ExpectedToFail annotation causes ClassCastException in RunResultsCache.addResults() (#188)
* Create extra specifications, and move ExpectedToFail example from Example spec to a linked test-dummies spec, so that Example spec is now green rather than grey

Example changes

---

src/main/java/org/concordion/Concordion.java
src/main/java/org/concordion/api/SpecificationByExample.java
src/main/java/org/concordion/integration/junit4/ConcordionRunner.java
src/main/java/org/concordion/internal/FixtureRunner.java
src/main/java/org/concordion/internal/RunOutput.java
src/main/java/org/concordion/internal/SpecificationToSpecificationByExampleAdaptor.java
src/main/java/org/concordion/internal/XMLSpecification.java
src/main/java/org/concordion/internal/cache/CompositeRunOutput.java
src/main/java/org/concordion/internal/cache/ConcordionRunOutput.java
src/main/java/org/concordion/internal/cache/RunResultsCache.java
src/main/java/org/concordion/internal/command/SpecificationCommand.java
src/main/java/org/concordion/internal/runner/DefaultConcordionRunner.java
src/test/java/org/concordion/internal/runner/CachedResultsUnitTest.java
src/test/java/spec/concordion/results/runTotals/RunTotalsFixture.java

Rework implementation of result recording to fix issue with ParallelRunExtension, and simplify the handling of results. See individual commits for details.
There are some whitespace changes. You should be able to add `?w=1` to the URL to ignore whitespace - however this wasn't working for me. You can see the diff without whitespace changes at https://github.com/concordion/concordion/compare/master...nigelcharman:restructure-result-recording?w=1.

Restructure result recording

---

src/main/java/org/concordion/api/extension/ConcordionExtender.java
src/main/java/org/concordion/api/listener/OuterExampleEvent.java
src/main/java/org/concordion/api/listener/OuterExampleListener.java
src/main/java/org/concordion/internal/ConcordionBuilder.java
src/main/java/org/concordion/internal/command/SpecificationCommand.java

In order for the parallel run extension to wait for each example to finish requires a listener for the "outer" example (which includes all commands in a specification not inside an example command) in addition to the existing example listener (which is only triggered for example commands).
Needed for concordion/concordion-parallel-run-extension#3.

Add outer example listener.

---

src/test/resources/spec/concordion/annotation/ImplementationStatus.html

concordion/concordion/build/reports/spec/concordion/annotation/ImplementationStatus.html was not displayed in chrome and firefox browsers due to missing demo.js and demo.css.
Should they be referenced from build/resource directory or just not be present for this spec?

ImplementationStatus.html report is not displaying in chrome and firefox

---

src/main/java/org/concordion/internal/parser/support/ConciseExpressionParser.java
src/test/resources/spec/concordion/specificationType/markdown/MarkdownExecuteCommand.md

For cases where the user wants the example name to be empty (eg. table headers).
This could be achieved using c:example=, but the '=' sign is confusing.
This can now be achieved using c:example.

Allow Markdown execute command to not require an attribute

---

src/main/java/org/concordion/internal/parser/markdown/ConcordionHtmlSerializer.java
src/main/java/org/concordion/internal/parser/support/ConciseExpressionParser.java
src/test/resources/spec/concordion/specificationType/markdown/Markdown.md
src/test/resources/spec/concordion/specificationType/markdown/MarkdownExecuteCommand.md
src/test/resources/spec/concordion/specificationType/markdown/MarkdownGrammar.markdown

The concise format was breaking some existing specs for users.
The example command now needs to be explicitly stated in the column header, eg. `[ ](- "#z=add(#x, #y)")[Example Name](- "c:example")`
As an alternative, you can use the `@` symbol instead of `c:example`, eg. `[ ](- "#z=add(#x, #y)")[Example Name](- "@")`

Removed concise table format.

---

src/main/java/org/concordion/internal/ConcordionBuilder.java

Fixes #241. The ThrowableCaughtListener for the extension was being added before the main throwable listener.
This meant that the exception had not been handled by the main listener prior to the extension attempting to modify it.
Modified ConcordionBuilder to add the main throwable listener first.

Modified ThrowableCaughtListener handling

---

src/main/java/org/concordion/integration/junit3/ConcordionTestCase.java
src/main/java/org/concordion/integration/junit4/ConcordionRunner.java
src/main/java/org/concordion/integration/junit4/JUnit4FrameworkProvider.java
src/main/java/org/concordion/internal/FixtureRunner.java

WIP: This pull request relates to #249. It demonstrates the idea on how third party frameworks could hook into Concordion and also provide their own SpecificationLocator implementations. The given implementation might be incomplete; it is however the less invasive option to show the idea behind.

Makes Concordion extendable by other frameworks

---

.travis.yml

Since oraclejdk7 is no longer supported - https://github.com/travis-ci/travis-ci/issues/7884.
It appears that openjdk6 is not supported either.

Remove openjdk6 and change JDK7 to openjdk7

---

src/main/java/org/concordion/internal/FixtureSpecificationMapper.java

From https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html, instances of this class are not safe for use by multiple concurrent threads.
This fix wraps the ServiceLoader instance in a ThreadLocal so we have one ServiceLoader per thread.
Fixes #259.

Fix thread-safety issue in FixtureSpecificationMapper.

---

src/main/java/org/concordion/internal/SimpleEvaluator.java
src/main/java/org/concordion/internal/command/executeCommand/modificationStrategies/ExecuteCommandTableModification.java
src/test/java/spec/concordion/common/command/execute/ExecutingTablesTest.java
src/test/resources/spec/concordion/common/command/execute/ExecutingTables.html

Implemented a special variable `#ROW` which is populated when the `execute` command runs on a `<table>` element. When each row of the table is executed the variable contains a map of the row cells, with the header cell contents as the key and the row cell contents as the value.
Fixes #313 and fixes #316.

Issue 313 access table data in a map

---

.github/workflows/ci.yml

so that workflow checks for successful builds across multiple JDKs

Add build and javadoc tasks to Gradle

---

build.gradle
gradle.properties

These are mostly used by extensions but may be required at compile time by some users as well.

Add more libraries to api rather than implementation.

---

src/main/java/org/concordion/internal/FixtureType.java

Related to the issue #285, I've made a fix to skip the jars that cannot be loaded due to an error that only happens in Java 9 or later versions when external resources are added to the fixture:
```
@ConcordionResources({
"/_concordion/resources/header.png",
"/_concordion/resources/concordion.css"
})
public abstract class AbstractFixture {
//...
}
```
This is a workaround solution using the best effort strategy. As for most of the projects using Concordion, we only load resources that lies within the same project structure, so it's quite unusual to load resources from external libraries.
Feel free to improve the code as youse want, but the way as is now, it should help a lot of legacy projects using newer java versions.

#285 workaround to skip resources that cannot be loaded as File

---

build.gradle

Version 3.0.0 not found since JCenter was deprecated in 2021

Fix git-publish plugin version not found

---

build.gradle
src/main/java/org/concordion/integration/junit4/ConcordionRunner.java
src/main/java/org/concordion/internal/ConcordionBuilder.java
src/main/java/org/concordion/internal/ResourceFinder.java
src/main/java/org/concordion/internal/extension/FixtureExtensionLoader.java

- Specs were failing with JUnit Vintage because the `ConcordionRunner` was instantiating the fixture object too soon in its constructor. After modifying the `ConcordionRunner`, the specs (as-is, without changes) are now working on JUnit 4 and JUnit Vintage.
- Also fixed `ResourceFinder` which was failing on Windows

Update to JUnit 5 and use JUnit Vintage
